version: "3.8"

services:
  ollama-api:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      # Aponta para o host do Docker (onde o Piper está escutando na porta 5000)
      - PIPER_HOST=http://host.docker.internal:5000
    # Garante que `host.docker.internal` seja mapeado para o gateway do host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ollama-api-data:/caminho/no/container
    restart: unless-stopped

volumes:
  ollama-api-data:
